package com.amazon.webservices.awsecommerceservice._2013_08_01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.2
 * Sun Feb 25 18:08:44 GMT 2018
 * Generated source version: 2.1.2
 *
 */

@WebService(targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", name = "AWSECommerceServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = ParameterStyle.BARE)
public interface AWSECommerceServicePortType {

    @WebMethod(operationName = "CartGet", action = "http://soap.amazon.com/CartGet")
    @WebResult(name = "CartGetResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public CartGetResponse cartGet(
            @WebParam(partName = "body", name = "CartGet", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    CartGet body
    );

    @WebMethod(operationName = "CartModify", action = "http://soap.amazon.com/CartModify")
    @WebResult(name = "CartModifyResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public CartModifyResponse cartModify(
            @WebParam(partName = "body", name = "CartModify", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    CartModify body
    );

    @WebMethod(operationName = "BrowseNodeLookup", action = "http://soap.amazon.com/BrowseNodeLookup")
    @WebResult(name = "BrowseNodeLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public BrowseNodeLookupResponse browseNodeLookup(
            @WebParam(partName = "body", name = "BrowseNodeLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    BrowseNodeLookup body
    );

    @WebMethod(operationName = "CartCreate", action = "http://soap.amazon.com/CartCreate")
    @WebResult(name = "CartCreateResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public CartCreateResponse cartCreate(
            @WebParam(partName = "body", name = "CartCreate", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    CartCreate body
    );

    @WebMethod(operationName = "CartAdd", action = "http://soap.amazon.com/CartAdd")
    @WebResult(name = "CartAddResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public CartAddResponse cartAdd(
            @WebParam(partName = "body", name = "CartAdd", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    CartAdd body
    );

    @WebMethod(operationName = "SimilarityLookup", action = "http://soap.amazon.com/SimilarityLookup")
    @WebResult(name = "SimilarityLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public SimilarityLookupResponse similarityLookup(
            @WebParam(partName = "body", name = "SimilarityLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    SimilarityLookup body
    );

    @WebMethod(operationName = "ItemLookup", action = "http://soap.amazon.com/ItemLookup")
    @WebResult(name = "ItemLookupResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public ItemLookupResponse itemLookup(
            @WebParam(partName = "body", name = "ItemLookup", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    ItemLookup body
    );

    @WebMethod(operationName = "ItemSearch", action = "http://soap.amazon.com/ItemSearch")
    @WebResult(name = "ItemSearchResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public ItemSearchResponse itemSearch(
            @WebParam(partName = "body", name = "ItemSearch", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    ItemSearch body
    );

    @WebMethod(operationName = "CartClear", action = "http://soap.amazon.com/CartClear")
    @WebResult(name = "CartClearResponse", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01", partName = "body")
    public CartClearResponse cartClear(
            @WebParam(partName = "body", name = "CartClear", targetNamespace = "http://webservices.amazon.com/AWSECommerceService/2013-08-01")
                    CartClear body
    );
}
